<!DOCTYPE html>
<html>
<head><meta name="generator" content="Hexo 3.8.0">
    

    

    



    <meta charset="utf-8">
    
    
    
    
    <title>java异常 | YGQ&#39;s Notes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <meta name="theme-color" content="#3F51B5">
    
    
    <meta name="keywords" content="Java异常">
    <meta name="description" content="整理了java异常的相关知识">
<meta name="keywords" content="Java异常">
<meta property="og:type" content="article">
<meta property="og:title" content="java异常">
<meta property="og:url" content="http://yoursite.com/2019/04/10/java异常/index.html">
<meta property="og:site_name" content="YGQ&#39;s Notes">
<meta property="og:description" content="整理了java异常的相关知识">
<meta property="og:locale" content="zh-Hans">
<meta property="og:updated_time" content="2019-11-25T08:21:05.975Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="java异常">
<meta name="twitter:description" content="整理了java异常的相关知识">
    
    <link rel="shortcut icon" href="/img/myblog.jpeg">
    <link rel="stylesheet" href="//unpkg.com/hexo-theme-material-indigo@latest/css/style.css">
    <script>window.lazyScripts=[]</script>

    <!-- custom head -->
    

</head>

<body>
    <div id="loading" class="active"></div>

    <aside id="menu" class="hide">
  <div class="inner flex-row-vertical">
    <a href="javascript:;" class="header-icon waves-effect waves-circle waves-light" id="menu-off">
        <i class="icon icon-lg icon-close"></i>
    </a>
    <div class="brand-wrap" style="background-image:url(/img/brand.jpg)">
      <div class="brand">
        <a href="/" class="avatar waves-effect waves-circle waves-light">
          <img src="/img/myblog.jpeg">
        </a>
        <hgroup class="introduce">
          <h5 class="nickname">YGQ</h5>
          <a href="mailto:594yangguanqun@163.com" title="594yangguanqun@163.com" class="mail">594yangguanqun@163.com</a>
        </hgroup>
      </div>
    </div>
    <div class="scroll-wrap flex-col">
      <ul class="nav">
        
            <li class="waves-block waves-effect">
              <a href="/">
                <i class="icon icon-lg icon-home"></i>
                Home
              </a>
            </li>
        
            <li class="waves-block waves-effect">
              <a href="/archives">
                <i class="icon icon-lg icon-archives"></i>
                Archives
              </a>
            </li>
        
            <li class="waves-block waves-effect">
              <a href="/tags">
                <i class="icon icon-lg icon-tags"></i>
                Tags
              </a>
            </li>
        
            <li class="waves-block waves-effect">
              <a href="/categories">
                <i class="icon icon-lg icon-th-list"></i>
                Categories
              </a>
            </li>
        
      </ul>
    </div>
  </div>
</aside>

    <main id="main">
        <header class="top-header" id="header">
    <div class="flex-row">
        <a href="javascript:;" class="header-icon waves-effect waves-circle waves-light on" id="menu-toggle">
          <i class="icon icon-lg icon-navicon"></i>
        </a>
        <div class="flex-col header-title ellipsis">java异常</div>
        
        <div class="search-wrap" id="search-wrap">
            <a href="javascript:;" class="header-icon waves-effect waves-circle waves-light" id="back">
                <i class="icon icon-lg icon-chevron-left"></i>
            </a>
            <input type="text" id="key" class="search-input" autocomplete="off" placeholder="検索">
            <a href="javascript:;" class="header-icon waves-effect waves-circle waves-light" id="search">
                <i class="icon icon-lg icon-search"></i>
            </a>
        </div>
        
        
        <a href="javascript:;" class="header-icon waves-effect waves-circle waves-light" id="menuShare">
            <i class="icon icon-lg icon-share-alt"></i>
        </a>
        
    </div>
</header>
<header class="content-header post-header">

    <div class="container fade-scale">
        <h1 class="title">java异常</h1>
        <h5 class="subtitle">
            
                <time datetime="2019-04-10T11:17:31.000Z" itemprop="datePublished" class="page-time">
  2019-04-10
</time>


	<ul class="article-category-list"><li class="article-category-list-item"><a class="article-category-list-link" href="/categories/Java/">Java</a></li></ul>

            
        </h5>
    </div>

    


</header>


<div class="container body-wrap">
    
    <aside class="post-widget">
        <nav class="post-toc-wrap post-toc-shrink" id="post-toc">
            <h4>TOC</h4>
            <ol class="post-toc"><li class="post-toc-item post-toc-level-2"><a class="post-toc-link" href="#异常的概念和层级"><span class="post-toc-number">1.</span> <span class="post-toc-text">异常的概念和层级</span></a><ol class="post-toc-child"><li class="post-toc-item post-toc-level-3"><a class="post-toc-link" href="#什么是Java异常"><span class="post-toc-number">1.1.</span> <span class="post-toc-text">什么是Java异常</span></a></li><li class="post-toc-item post-toc-level-3"><a class="post-toc-link" href="#异常的层级"><span class="post-toc-number">1.2.</span> <span class="post-toc-text">异常的层级</span></a></li></ol></li><li class="post-toc-item post-toc-level-2"><a class="post-toc-link" href="#Java的异常处理机制"><span class="post-toc-number">2.</span> <span class="post-toc-text">Java的异常处理机制</span></a><ol class="post-toc-child"><li class="post-toc-item post-toc-level-3"><a class="post-toc-link" href="#异常处理的基本语法"><span class="post-toc-number">2.1.</span> <span class="post-toc-text">异常处理的基本语法</span></a><ol class="post-toc-child"><li class="post-toc-item post-toc-level-4"><a class="post-toc-link" href="#1-try-catch"><span class="post-toc-number">2.1.1.</span> <span class="post-toc-text">1. try-catch</span></a></li><li class="post-toc-item post-toc-level-4"><a class="post-toc-link" href="#2-throw"><span class="post-toc-number">2.1.2.</span> <span class="post-toc-text">2. throw</span></a></li><li class="post-toc-item post-toc-level-4"><a class="post-toc-link" href="#3-throws"><span class="post-toc-number">2.1.3.</span> <span class="post-toc-text">3. throws</span></a></li><li class="post-toc-item post-toc-level-4"><a class="post-toc-link" href="#4-finally"><span class="post-toc-number">2.1.4.</span> <span class="post-toc-text">4. finally</span></a></li></ol></li><li class="post-toc-item post-toc-level-3"><a class="post-toc-link" href="#异常链"><span class="post-toc-number">2.2.</span> <span class="post-toc-text">异常链</span></a></li></ol></li><li class="post-toc-item post-toc-level-2"><a class="post-toc-link" href="#自定义异常"><span class="post-toc-number">3.</span> <span class="post-toc-text">自定义异常</span></a></li></ol><li class="post-toc-item post-toc-level-1"><a class="post-toc-link" href="#异常的使用"><span class="post-toc-number"></span> <span class="post-toc-text">异常的使用</span></a>
        </li></nav>
    </aside>


<article id="post-java异常" class="post-article article-type-post fade" itemprop="blogPost">

    <div class="post-card">
        <h1 class="post-card-title">java异常</h1>
        <div class="post-meta">
            <time class="post-time" title="2019-04-10 19:17:31" datetime="2019-04-10T11:17:31.000Z" itemprop="datePublished">2019-04-10</time>

            
	<ul class="article-category-list"><li class="article-category-list-item"><a class="article-category-list-link" href="/categories/Java/">Java</a></li></ul>



            

        </div>
        <div class="post-content" id="post-content" itemprop="postContent">
            <p><em>整理了java异常的相关知识</em></p>
<a id="more"></a>
<h2 id="异常的概念和层级"><a href="#异常的概念和层级" class="headerlink" title="异常的概念和层级"></a>异常的概念和层级</h2><h3 id="什么是Java异常"><a href="#什么是Java异常" class="headerlink" title="什么是Java异常"></a>什么是Java异常</h3><p>异常是发生在程序执行过程中阻碍程序正常执行的错误事件。比如：用户输入错误数据、硬件故障、网络阻塞等都会导致出现异常。 只要在Java语句执行中产生了异常，一个异常对象就会被创建，JRE就会试图寻找异常处理程序来处理异常。如果有合适的异常处理程序，异常对象就会被异常处理程序接管，否则，将引发运行环境异常，JRE终止程序执行。 Java异常处理框架只能处理运行时错误，编译错误不在其考虑范围之内。</p>
<h3 id="异常的层级"><a href="#异常的层级" class="headerlink" title="异常的层级"></a>异常的层级</h3><p><code>Throwable</code>在异常类的层次结构的顶层，有两个分支： <strong>Error</strong> 和 <strong>Exception</strong>。其中 Error 用来表示 JVM 无法处理的错误，Exception 分为两种：</p>
<ul>
<li><strong>受检异常</strong> ：要么使用<code>try-catch</code>语句进行捕获，要么用<code>throws</code>子句抛出，否则编译无法通过。</li>
<li><strong>非受检异常/运行时异常</strong> ：(<code>RuntimeException</code>)是程序运行时错误，例如除 0 会引发 Arithmetic Exception，此时程序崩溃并且无法恢复。</li>
</ul>
<p>非受检异常（<code>unchecked exception</code>），即<code>Error</code>和<code>RuntimeException</code>及其子类。</p>
<p><code>Error</code>：<code>Error</code>类对象由 Java 虚拟机生成并抛出，大多数错误与代码编写者所执行的操作无关。例如，Java虚拟机运行错误（<code>Virtual MachineError</code>），当JVM不再有继续执行操作所需的内存资源时，将出现 <code>OutOfMemoryError</code>。这些异常发生时，Java虚拟机（JVM）一般会选择线程终止；还有发生在虚拟机试图执行应用时，如类定义错误（<code>NoClassDefFoundError</code>）、链接错误（<code>LinkageError</code>）。这些错误是不可查的，因为它们在应用程序的控制和处理能力之 外，而且绝大多数是程序运行时不允许出现的状况。对于设计合理的应用程序来说，即使确实发生了错误，本质上也不应该试图去处理它所引起的异常状况。在Java中，错误通常是使用<code>Error</code>的子类描述。</p>
<p><code>Exception</code>：在<code>Exception</code>分支中有一个重要的子类<code>RuntimeException</code>（运行时异常），该类型的异常自动为你所编写的程序定义<code>ArrayIndexOutOfBoundsException</code>（数组下标越界）、<code>NullPointerException</code>（空指针异常）、<code>ArithmeticException</code>（算术异常）、<code>MissingResourceException</code>（丢失资源）、<code>ClassNotFoundException</code>（找不到类）等异常，这些异常是非受检异常，程序中可以选择捕获处理，也可以不处理。这些异常一般是由程序逻辑错误引起的，程序应尽可能避免；而<code>RuntimeException</code>之外的异常我们统称为非运行时异常，是必须进行处理的异常，否则程序就不能编译通过。如<code>IOException</code>、<code>SQLException</code>等以及用户自定义的<code>Exception</code>异常，一般情况下不自定义检查异常。</p>
<p>注意：</p>
<p><code>Error</code>和<code>Exception</code>的区别：<code>Error</code>通常是灾难性的致命的错误，是程序无法控制和处理的，当出现这些异常时，Java虚拟机（JVM）一般会选择终止线程；<code>Exception</code>通常情况下是可以被程序处理的，并且在程序中应该尽可能的去处理这些异常。</p>
<p><code>非受检异常</code>为编译器不要求强制处理的异常， <code>受检异常</code>则是编译器要求必须处置的异常。</p>
<h2 id="Java的异常处理机制"><a href="#Java的异常处理机制" class="headerlink" title="Java的异常处理机制"></a>Java的异常处理机制</h2><p>Java的异常处理本质上是抛出异常和捕获异常。</p>
<ul>
<li><code>抛出异常</code>：要理解抛出异常，首先要明白什么是异常情形（exception condition），它是指阻止当前方法或作用域继续执行的问题。其次把异常情形和普通问题相区分，普通问题是指在当前环境下能得到足够的信息，总能处理这个错误。对于异常情形，已经无法继续下去了，因为在当前环境下无法获得必要的信息来解决问题，你所能做的就是从当前环境中跳出，并把问题提交给上一级环境，这就是抛出异常时所发生的事情。</li>
</ul>
<p>抛出异常后，会有几件事随之发生。首先，是使用<code>new</code>在堆上创建一个异常对象；然后，当前的执行路径（已经无法继续下去了）被终止，并且从当前环境中弹出对异常对象的引用。此时，异常处理机制接管程序，并开始寻找一个恰当的地方继续执行程序，这个恰当的地方就是异常处理程序或者异常处理器，它的任务是将程序从错误状态中恢复，以使程序要么换一种方式运行，要么继续运行下去。</p>
<ul>
<li><code>捕获异常</code>：在方法抛出异常之后，运行时系统将转为寻找合适的异常处理器（exception handler）。潜在的异常处理器是异常发生时依次存留在调用栈中的方法的集合。当异常处理器所能处理的异常类型与方法抛出的异常类型相符时，即为合适的异常处理器。运行时系统从发生异常的方法开始，依次回查调用栈中的方法，直至找到含有合适异常处理器的方法并执行。当运行时系统遍历调用栈而未找到合适的异常处理器，则运行时系统终止。同时，意味着Java程序的终止。</li>
</ul>
<h3 id="异常处理的基本语法"><a href="#异常处理的基本语法" class="headerlink" title="异常处理的基本语法"></a>异常处理的基本语法</h3><p>Java异常处理涉及到五个关键字，分别是：<code>try</code>、<code>catch</code>、<code>finally</code>、<code>throw</code>、<code>throws</code>。</p>
<h4 id="1-try-catch"><a href="#1-try-catch" class="headerlink" title="1. try-catch"></a>1. try-catch</h4><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line">try&#123;</span><br><span class="line">    //code that might generate exceptions    </span><br><span class="line">&#125;catch(Exception e)&#123;</span><br><span class="line">    //the code of handling exception1</span><br><span class="line">&#125;catch(Exception e)&#123;</span><br><span class="line">    //the code of handling exception2</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>要明白异常捕获，还要理解<code>监控区域</code>（guarded region）的概念。它是一段可能产生异常的代码，并且后面跟着处理这些异常的代码。</p>
<p>因而可知，上述<code>try-catch</code>所描述的即是监控区域，关键词<code>try</code>后的一对大括号将一块可能发生异常的代码包起来，即为监控区域。Java方法在运行过程中发生了异常，则创建异常对象。将异常抛出监控区域之外，由Java运行时系统负责寻找匹配的<code>catch</code>子句来捕获异常。若有一个<code>catch</code>语句匹配到了，则执行该<code>catch</code>块中的异常处理代码，就不再尝试匹配别的<code>catch</code>块了。</p>
<p>（匹配的原则是：如果抛出的异常对象属于<code>catch</code>子句的异常类，或者属于该异常类的子类，则认为生成的异常对象与<code>catch</code>块捕获的异常类型相匹配。）</p>
<p>举个例子算术异常：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line">public class TestException &#123;  </span><br><span class="line">    public static void main(String[] args) &#123;  </span><br><span class="line">        int a = 1;  </span><br><span class="line">        int b = 0;  </span><br><span class="line">        try &#123; // try监控区域               </span><br><span class="line">            if (b == 0) throw new ArithmeticException(); // 通过throw语句抛出异常  </span><br><span class="line">            System.out.println(&quot;a/b的值是：&quot; + a / b);  </span><br><span class="line">            System.out.println(&quot;this will not be printed!&quot;);</span><br><span class="line">        &#125;  </span><br><span class="line">        catch (ArithmeticException e) &#123; // catch捕捉异常  </span><br><span class="line">            System.out.println(&quot;程序出现异常&quot;+e);  </span><br><span class="line">        &#125;  </span><br><span class="line">        System.out.println(&quot;程序正常结束。&quot;);  </span><br><span class="line">    &#125;  </span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">运行结果是：</span><br><span class="line">D:\java&gt;java TestException</span><br><span class="line"> </span><br><span class="line">程序出现异常java.lang.ArithmeticException</span><br><span class="line"></span><br><span class="line">程序正常结束。</span><br></pre></td></tr></table></figure>
<p>（<code>Throwable</code>重载了<code>toString()</code>方法（由<code>Object</code>定义），所以它将返回一个包含异常描述的字符串。）</p>
<p>根据前面讲述的，算术异常属于运行时异常，因而实际上该异常不需要程序抛出，运行时系统自动抛出，将例子改为如下：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line">public class TestException &#123;  </span><br><span class="line">    public static void main(String[] args) &#123;  </span><br><span class="line">        int a = 1;  </span><br><span class="line">        int b = 0;    </span><br><span class="line">        System.out.println(&quot;a/b的值是：&quot; + a / b);</span><br><span class="line">        System.out.println(&quot;this will not be printed!&quot;);</span><br><span class="line">    &#125;  </span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line">运行结果如下：</span><br><span class="line">D:\java&gt;java TestException</span><br><span class="line"></span><br><span class="line">Exception in thread &quot;main&quot; java.lang.ArithmeticException: / by zero</span><br><span class="line">    at TestException.main(TestException.java:7)</span><br></pre></td></tr></table></figure>
<p><code>使用多重的catch语句</code>：很多情况下，由单个的代码段可能引起多个异常。处理这种情况，我们需要定义两个或者更多的<code>catch</code>子句，每个子句捕获一种类型的异常，当异常被引发时，每个<code>catch</code>子句被依次检查，第一个匹配异常类型的子句执行，当一个<code>catch</code>子句执行以后，其他的子句将被旁路。</p>
<p>注意：</p>
<p>如果多个 catch 块中的异常出现继承关系，<strong>父类异常 catch 块放在最下面</strong>。否则，在异常捕获时，小的异常将不能被捕获，因为全在大的异常类中捕获到。</p>
<p><code>嵌套try语句</code>：<code>try</code>语句可以被嵌套。也就是说，一个<code>try</code>语句可以在另一个<code>try</code>块的内部。每次进入<code>try</code>语句，异常的前后关系都会被推入堆栈。如果一个内部的<code>try</code>语句不含特殊异常的<code>catch</code>处理程序，堆栈将弹出，下一个<code>try</code>语句的<code>catch</code>处理程序将检查是否与之匹配。这个过程将继续直到一个<code>catch</code>语句被匹配成功，或者是直到所有的嵌套<code>try</code>语句被检查完毕。如果没有<code>catch</code>语句匹配，Java运行时系统将处理这个异常。</p>
<p>举个例子嵌套<code>try</code>：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br></pre></td><td class="code"><pre><span class="line">class NestTry&#123;</span><br><span class="line">    public static void main(String[] args)&#123;</span><br><span class="line">        try&#123;</span><br><span class="line">            int a = args.length;</span><br><span class="line">            int b = 42 / a;</span><br><span class="line">            System.out.println(&quot;a = &quot;+ a);</span><br><span class="line">            try&#123;</span><br><span class="line">                if(a == 1)&#123;</span><br><span class="line">                a = a/(a-a);</span><br><span class="line">                &#125;</span><br><span class="line">                if(a == 2)&#123;</span><br><span class="line">                    int c[] = &#123;1&#125;;</span><br><span class="line">                    c[42] =99;</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;catch(ArrayIndexOutOfBoundsException e)&#123;</span><br><span class="line">                System.out.println(&quot;ArrayIndexOutOfBounds :&quot;+e);</span><br><span class="line">            &#125;    </span><br><span class="line">        &#125;catch(ArithmeticException e)&#123;</span><br><span class="line">            System.out.println(&quot;Divide by 0&quot;+ e);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>正如程序中所显示的，该程序在一个try块中嵌套了另一个<code>try</code>块。程序工作如下：当你在没有命令行参数的情况下执行该程序，外面的<code>try</code>块将产生一个被0除的异常。程序在有一个命令行参数条件下执行，由嵌套的<code>try</code>块产生一个被0除的异常，由于内部的<code>catch</code>块不匹配这个异常，它将把异常传给外部的<code>try</code>块，在外部异常被处理。如果你在具有两个命令行参数的条件下执行该程序，将由内部<code>try</code>块产生一个数组边界异常。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line">程序执行结果如下：</span><br><span class="line">D:\java&gt;javac estTry.java</span><br><span class="line"></span><br><span class="line">D:\java&gt;&gt;java NestTry</span><br><span class="line"></span><br><span class="line">Divide by 0 java.lang.ArithmeticExceptio: / by zero</span><br><span class="line"></span><br><span class="line">D:\java&gt;java NestTry one</span><br><span class="line"></span><br><span class="line">a = 1</span><br><span class="line"></span><br><span class="line">Divide by 0java.lang.ArithmeticException: / by zero</span><br><span class="line"></span><br><span class="line">D:\java&gt;java NestTry one two</span><br><span class="line"></span><br><span class="line">a = 2</span><br><span class="line"></span><br><span class="line">ArrayIndexOutOfBounds :java.lang.ArrayIndexOutOfBoundsException: 42</span><br></pre></td></tr></table></figure>
<p> 提示</p>
<p>当有方法调用时，<code>try</code>语句的嵌套可以很隐蔽的发生。例如，我们可以将对方法的调用放在一个<code>try</code>块中。在该方法的内部，有另一个<code>try</code>语句。在这种情况下，方法内部的<code>try</code>仍然是嵌套在外部调用该方法的<code>try</code>块中的。下面我们将对上述例子进行修改，嵌套的<code>try</code>块移到方法nesttry()的内部：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br></pre></td><td class="code"><pre><span class="line">class NestTry&#123;</span><br><span class="line">    static void nesttry(int a)&#123;</span><br><span class="line">        try&#123;</span><br><span class="line">            if(a == 1)&#123;</span><br><span class="line">                a = a/(a-a);</span><br><span class="line">            &#125;</span><br><span class="line">            if(a == 2)&#123;</span><br><span class="line">                int c[] = &#123;1&#125;;</span><br><span class="line">                c[42] =99;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;catch(ArrayIndexOutOfBoundsException e)&#123;</span><br><span class="line">            System.out.println(&quot;ArrayIndexOutOfBounds :&quot;+e);</span><br><span class="line">        &#125;    </span><br><span class="line">    &#125;</span><br><span class="line">    public static void main(String[] args)&#123;</span><br><span class="line">        try&#123;</span><br><span class="line">            int a = args.length;</span><br><span class="line">            int b = 42 / a;</span><br><span class="line">            System.out.println(&quot;a = &quot;+ a);</span><br><span class="line">            nesttry(a);</span><br><span class="line">        &#125;catch(ArithmeticException e)&#123;</span><br><span class="line">            System.out.println(&quot;Divide by 0&quot;+ e);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line">结果输出与前面的例子一致：</span><br><span class="line">D:\java&gt;javac NestTry.java</span><br><span class="line"></span><br><span class="line">D:\java&gt;java NestTry</span><br><span class="line"></span><br><span class="line">Divide by 0java.lang.ArithmeticException: / by zero</span><br><span class="line"></span><br><span class="line">D:\java&gt;java NestTry one</span><br><span class="line"></span><br><span class="line">a = 1</span><br><span class="line"></span><br><span class="line">Divide by 0java.lang.ArithmeticException: / by zero</span><br><span class="line"></span><br><span class="line">D:\java&gt;java NestTry one two</span><br><span class="line"></span><br><span class="line">a = 2</span><br><span class="line"></span><br><span class="line">ArrayIndexOutOfBounds :java.lang.ArrayIndexOutOfBoundsException: 42</span><br></pre></td></tr></table></figure>
<h4 id="2-throw"><a href="#2-throw" class="headerlink" title="2. throw"></a>2. throw</h4><p>使用在函数内；用于抛出明确的异常。<code>Throw</code>的语法形式如下：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">throw ThrowableInstance;</span><br></pre></td></tr></table></figure>
<p>这里的ThrowableInstance一定是<code>Throwable</code>类类型或者<code>Throwable</code>子类类型的一个对象。基本数据类型以及非<code>Throwable</code>类，例如<code>String</code>或<code>Object</code>，不能用作异常。有两种方法可以获取<code>Throwable</code>对象：在<code>catch</code>子句中使用参数或者使用<code>new</code>操作符创建。</p>
<p>程序执行完<code>throw</code>语句之后立即停止；<code>throw</code>后面的任何语句不被执行，最邻近的<code>try</code>块用来检查它是否含有一个与异常类型匹配的<code>catch</code>语句。如果发现了匹配的块，控制转向该语句；如果没有发现，次包围的<code>try</code>块来检查，以此类推。如果没有发现匹配的<code>catch</code>块，默认异常处理程序中断程序的执行并且打印堆栈轨迹。</p>
<p>例子创建并抛出异常：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line">class TestThrow&#123;</span><br><span class="line">    static void proc()&#123;</span><br><span class="line">        try&#123;</span><br><span class="line">            throw new NullPointerException(&quot;demo&quot;);</span><br><span class="line">        &#125;catch(NullPointerException e)&#123;</span><br><span class="line">            System.out.println(&quot;Caught inside proc&quot;);</span><br><span class="line">            throw e;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    public static void main(String [] args)&#123;</span><br><span class="line">        try&#123;</span><br><span class="line">            proc();</span><br><span class="line">        &#125;catch(NullPointerException e)&#123;</span><br><span class="line">            System.out.println(&quot;Recaught: &quot;+e);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">运行结果：</span><br><span class="line">D:\java&gt;java TestThrow</span><br><span class="line"></span><br><span class="line">Caught inside proc</span><br><span class="line"></span><br><span class="line">Recaught: java.lang.NullPointerException: demo</span><br></pre></td></tr></table></figure>
<p>该程序两次处理相同的错误，首先，<code>main()</code>方法设立了一个异常关系然后调用proc()。proc()方法设立了另一个异常处理关系并且立即抛出一个<code>NullPointerException</code>实例，<code>NullPointerException</code>在<code>main()</code>中被再次捕获。</p>
<p>该程序阐述了怎样创建Java的标准异常对象，特别注意这一行：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">throw new NullPointerException(&quot;demo&quot;);</span><br></pre></td></tr></table></figure>
<p> 提示</p>
<p>此处<code>new</code>用来构造一个<code>NullPointerException</code>实例，所有的Java内置的运行时异常有两个构造方法：一个没有参数，一个带有一个字符串参数。当用第二种形式时，参数指定描述异常的字符串。如果对象用作<code>print()</code>或者<code>println()</code>的参数时，该字符串被显示。这同样可以通过调用getMessage()来实现，getMessage()是由<code>Throwable</code>定义的。</p>
<h4 id="3-throws"><a href="#3-throws" class="headerlink" title="3. throws"></a>3. throws</h4><p>使用在方法上；抛出异常类，可多个，用逗号隔开</p>
<p>下面是<code>throws</code>子句的方法声明的通用形式：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">public void info() throws Exception</span><br><span class="line">&#123;</span><br><span class="line">   //body of method</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>Exception 是该方法可能引发的所有的异常,也可以是异常列表，中间以逗号隔开。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line">class TestThrows&#123;</span><br><span class="line">    static void throw1() throws IllegalAccessException &#123;</span><br><span class="line">        System.out.println(&quot;Inside throw1 . &quot;);</span><br><span class="line">        throw new IllegalAccessException(&quot;demo&quot;);</span><br><span class="line">    &#125;</span><br><span class="line">    public static void main(String[] args)&#123;</span><br><span class="line">        try &#123;</span><br><span class="line">            throw1();</span><br><span class="line">        &#125;catch(IllegalAccessException e )&#123;</span><br><span class="line">            System.out.println(&quot;Caught &quot; + e);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p> 提示</p>
<p><code>Throws</code>抛出异常的规则：</p>
<ul>
<li>如果是不受检查异常（<code>unchecked exception</code>），即<code>Error</code>、<code>RuntimeException</code>或它们的子类，那么可以不使用<code>throws</code>关键字来声明要抛出的异常，编译仍能顺利通过，但在运行时会被系统抛出。</li>
<li></li>
<li>必须声明方法可抛出的任何检查异常（<code>checked exception</code>）。即如果一个方法可能出现受可查异常，要么用<code>try-catch</code>语句捕获，要么用<code>throws</code>子句声明将它抛出，否则会导致编译错误</li>
<li></li>
<li>仅当抛出了异常，该方法的调用者才必须处理或者重新抛出该异常。当方法的调用者无力处理该异常的时候，应该继续抛出，而不是囫囵吞枣。</li>
<li></li>
<li>调用方法必须遵循任何可查异常的处理和声明规则。若覆盖一个方法，则不能声明与覆盖方法不同的异常。声明的任何异常必须是被覆盖方法所声明异常的同类或子类。</li>
</ul>
<h4 id="4-finally"><a href="#4-finally" class="headerlink" title="4. finally"></a>4. finally</h4><p>当异常发生时，通常方法的执行将做一个陡峭的非线性的转向，它甚至会过早的导致方法返回。例如，如果一个方法打开了一个文件并关闭，然后退出，你不希望关闭文件的代码被异常处理机制旁路。<code>finally</code>关键字为处理这种意外而设计。</p>
<p><code>finally</code>创建的代码块在<code>try/catch</code>块完成之后另一个<code>try/catch</code>出现之前执行。<code>finally</code>块无论有没有异常抛出都会执行。如果抛出异常，即使没有<code>catch</code>子句匹配，<code>finally</code>也会执行。一个方法将从一个<code>try/catch</code>块返回到调用程序的任何时候，经过一个未捕获的异常或者是一个明确的返回语句，<code>finally</code>子句在方法返回之前仍将执行。这在关闭文件句柄和释放任何在方法开始时被分配的其他资源是很有用。</p>
<p> 提示</p>
<p><code>finally</code>子句是可选项，可以有也可以无，但是每个<code>try</code>语句至少需要一个<code>catch</code>或者<code>finally</code>子句。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br></pre></td><td class="code"><pre><span class="line">class TestFinally&#123;</span><br><span class="line">    static void proc1()&#123;</span><br><span class="line">        try&#123;</span><br><span class="line">            System.out.println(&quot;inside proc1&quot;);</span><br><span class="line">            throw new RuntimeException(&quot;demo&quot;);</span><br><span class="line">        &#125;finally&#123;</span><br><span class="line">            System.out.println(&quot;proc1&apos;s finally&quot;);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    static void proc2()&#123;</span><br><span class="line">        try&#123;</span><br><span class="line">            System.out.println(&quot;inside proc2&quot;);</span><br><span class="line">            return ;</span><br><span class="line">        &#125; finally&#123;</span><br><span class="line">            System.out.println(&quot;proc2&apos;s finally&quot;);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125; </span><br><span class="line">    static void proc3()&#123;</span><br><span class="line">        try&#123;</span><br><span class="line">            System.out.println(&quot;inside proc3&quot;);</span><br><span class="line">        &#125;finally&#123;</span><br><span class="line">            System.out.println(&quot;proc3&apos;s finally&quot;);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    public static void main(String [] args)&#123;</span><br><span class="line">        try&#123;</span><br><span class="line">            proc1();</span><br><span class="line">        &#125;catch(Exception e)&#123;</span><br><span class="line">            System.out.println(&quot;Exception caught&quot;);</span><br><span class="line">        &#125;</span><br><span class="line">        proc2();</span><br><span class="line">        proc3();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>该例子中，proc1()抛出了异常中断了<code>try</code>，它的<code>finally</code>子句在退出时执行。proc2的<code>try</code>语句通过<code>return</code>语句返回，但在返回之前<code>finally</code>语句执行。在proc3()中<code>try</code>语句正常执行，没有错误，<code>finally</code>语句也被执行。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line">程序输出结果：</span><br><span class="line">D:\java&gt;java TestFinally</span><br><span class="line"></span><br><span class="line">inside proc1</span><br><span class="line"></span><br><span class="line">proc1&apos;s finally</span><br><span class="line"></span><br><span class="line">Exception caught</span><br><span class="line"></span><br><span class="line">inside proc2</span><br><span class="line"> </span><br><span class="line">proc2&apos;s finally</span><br><span class="line"> </span><br><span class="line">inside proc3</span><br><span class="line"> </span><br><span class="line">proc3&apos;s finally</span><br></pre></td></tr></table></figure>
<p> 提示</p>
<p>如果<code>finally</code>块与一个<code>try</code>联合使用，<code>finally</code>块将在<code>try</code>结束之前执行。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br></pre></td><td class="code"><pre><span class="line">class TestFinally&#123;</span><br><span class="line">    static void proc1()&#123;</span><br><span class="line">        try&#123;</span><br><span class="line">            System.out.println(&quot;inside proc1&quot;);</span><br><span class="line">            throw new RuntimeException(&quot;demo&quot;);</span><br><span class="line">        &#125;finally&#123;</span><br><span class="line">            System.out.println(&quot;proc1&apos;s finally&quot;);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    static void proc2()&#123;</span><br><span class="line">        try&#123;</span><br><span class="line">            System.out.println(&quot;inside proc2&quot;);</span><br><span class="line">            return ;</span><br><span class="line">        &#125; finally&#123;</span><br><span class="line">            System.out.println(&quot;proc2&apos;s finally&quot;);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125; </span><br><span class="line">    static void proc3()&#123;</span><br><span class="line">        try&#123;</span><br><span class="line">            System.out.println(&quot;inside proc3&quot;);</span><br><span class="line">        &#125;finally&#123;</span><br><span class="line">            System.out.println(&quot;proc3&apos;s finally&quot;);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    public static void main(String [] args)&#123;</span><br><span class="line">        try&#123;</span><br><span class="line">            proc1();</span><br><span class="line">        &#125;catch(Exception e)&#123;</span><br><span class="line">            System.out.println(&quot;Exception caught&quot;);</span><br><span class="line">        &#125;</span><br><span class="line">        proc2();</span><br><span class="line">        proc3();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>该例子中，proc1()抛出了异常中断了<code>try</code>，它的<code>finally</code>子句在退出时执行。proc2的<code>try</code>语句通过<code>return</code>语句返回，但在返回之前<code>finally</code>语句执行。在proc3()中<code>try</code>语句正常执行，没有错误，<code>finally</code>语句也被执行。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line">程序输出结果：</span><br><span class="line">D:\java&gt;java TestFinally</span><br><span class="line"></span><br><span class="line">inside proc1</span><br><span class="line"></span><br><span class="line">proc1&apos;s finally</span><br><span class="line"></span><br><span class="line">Exception caught</span><br><span class="line"></span><br><span class="line">inside proc2</span><br><span class="line"> </span><br><span class="line">proc2&apos;s finally</span><br><span class="line"> </span><br><span class="line">inside proc3</span><br><span class="line"> </span><br><span class="line">proc3&apos;s finally</span><br></pre></td></tr></table></figure>
<p>提示</p>
<p>如果<code>finally</code>块与一个<code>try</code>联合使用，<code>finally</code>块将在<code>try</code>结束之前执行。</p>
<h3 id="异常链"><a href="#异常链" class="headerlink" title="异常链"></a>异常链</h3><p>Java这种<strong>向上传递异常信息的处理机制</strong>，形成异常链。将异常发生的原因一个传一个串起来，即把底层的异常信息传给上层，这样逐层抛出。</p>
<p>Java方法抛出的可查异常将依据调用栈、沿着方法调用的层次结构一直传递到具备处理能力的调用方法，最高层次到main方法为止。如果异常传递到main方法，而main不具备处理能力，也没有通过throws声明抛出该异常，将可能出现编译错误。</p>
<p> Java API文档中给出了一个简单的模型：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;   </span><br><span class="line">    lowLevelOp();   </span><br><span class="line">&#125; <span class="keyword">catch</span> (LowLevelException le) &#123;   </span><br><span class="line">    <span class="keyword">throw</span> (HighLevelException) <span class="keyword">new</span> HighLevelException().initCause(le);   </span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>当程序捕获到了一个底层异常，在处理部分选择了继续抛出一个更高级别的新异常给此方法的调用者。 这样异常的原因就会逐层传递。这样，位于高层的异常递归调用getCause()方法，就可以遍历各层的异常原因。 这就是<code>Java异常链</code>的原理。</p>
<h2 id="自定义异常"><a href="#自定义异常" class="headerlink" title="自定义异常"></a>自定义异常</h2><p>使用Java内置的异常类可以描述在编程时出现的大部分异常情况。除此之外，用户还可以自定义异常。用户自定义异常类，只需继承<code>Exception</code>类即可。</p>
<p>在程序中使用自定义异常类，大体可分为以下几个步骤:</p>
<ul>
<li>创建自定义异常类。</li>
<li>在方法中通过<code>throw</code>关键字抛出异常对象。</li>
<li>如果在当前抛出异常的方法中处理异常，可以使用<code>try-catch</code>语句捕获并处理；否则在方法的声明处通过<code>throws</code>关键字指明要抛出给方法调用者的异常，继续进行下一步操作。</li>
<li>在出现异常方法的调用者中捕获并处理异常。</li>
</ul>
<p>举例自定义异常：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br></pre></td><td class="code"><pre><span class="line">class MyException extends Exception &#123;</span><br><span class="line">    private int detail;</span><br><span class="line">    MyException(int a)&#123;</span><br><span class="line">        detail = a;</span><br><span class="line">    &#125;</span><br><span class="line">    public String toString()&#123;</span><br><span class="line">        return &quot;MyException [&quot;+ detail + &quot;]&quot;;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line">public class TestMyException&#123;</span><br><span class="line">    static void compute(int a) throws MyException&#123;</span><br><span class="line">        System.out.println(&quot;Called compute(&quot; + a + &quot;)&quot;);</span><br><span class="line">        if(a &gt; 10)&#123;</span><br><span class="line">            throw new MyException(a);</span><br><span class="line">        &#125;</span><br><span class="line">        System.out.println(&quot;Normal exit!&quot;);</span><br><span class="line">    &#125;</span><br><span class="line">    public static void main(String [] args)&#123;</span><br><span class="line">        try&#123;</span><br><span class="line">            compute(1);</span><br><span class="line">            compute(20);</span><br><span class="line">        &#125;catch(MyException me)&#123;</span><br><span class="line">            System.out.println(&quot;Caught &quot; + me);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>该例子完全按照上述步骤。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line">运行结果如下：</span><br><span class="line">D:\java&gt;java TestMyException</span><br><span class="line"></span><br><span class="line">Called compute(1)</span><br><span class="line"></span><br><span class="line">Normal exit!</span><br><span class="line"></span><br><span class="line">Called compute(20)</span><br><span class="line"></span><br><span class="line">Caught MyException [20]</span><br></pre></td></tr></table></figure>
<h1 id="异常的使用"><a href="#异常的使用" class="headerlink" title="异常的使用"></a>异常的使用</h1><ol>
<li>只在必要使用异常的地方才使用异常，不要用异常去控制程序的流程</li>
</ol>
<p>　　<strong>谨慎地使用异常，异常捕获的代价非常高昂，异常使用过多会严重影响程序的性能。</strong>如果在程序中能够用if语句和Boolean变量来进行逻辑判断，那么尽量减少异常的使用，从而避免不必要的异常捕获和处理。</p>
<ol start="2">
<li>切忌使用空catch块</li>
</ol>
<p>　　在捕获了异常之后什么都不做，相当于忽略了这个异常。千万不要使用空的catch块，空的catch块意味着你在程序中隐藏了错误和异常，并且很可能导致程序出现不可控的执行结果。如果你非常肯定捕获到的异常不会以任何方式对程序造成影响，最好用Log日志将该异常进行记录，以便日后方便更新和维护。</p>
<ol start="3">
<li>检查异常和非检查异常的选择</li>
</ol>
<p>　　一旦你决定抛出异常，你就要决定抛出什么异常。这里面的主要问题就是抛出检查异常还是非检查异常。</p>
<p>　　检查异常导致了太多的try…catch代码，可能有很多检查异常对开发人员来说是无法合理地进行处理的，比如SQLException，而开发人员却不得不去进行try…catch，这样就会导致经常出现这样一种情况：逻辑代码只有很少的几行，而进行异常捕获和处理的代码却有很多行。这样不仅导致逻辑代码阅读起来晦涩难懂，而且降低了程序的性能。</p>
<p>　　我个人建议尽量避免检查异常的使用，如果确实该异常情况的出现很普遍，需要提醒调用者注意处理的话，就使用检查异常；否则使用非检查异常。</p>
<p>　　因此，在一般情况下，我觉得<strong>尽量将检查异常转变为非检查异常交给上层处理</strong>。</p>
<ol start="4">
<li>注意catch块的顺序</li>
</ol>
<p>　　不要把上层类的异常放在最前面的catch块。比如下面这段代码：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">`<span class="keyword">try</span>` `&#123;``    ``FileInputStream inputStream = ``<span class="keyword">new</span>` `FileInputStream(``<span class="string">"d:/a.txt"</span>``);``    ``<span class="keyword">int</span>` `ch = inputStream.read();``    ``System.out.println(``<span class="string">"aaa"</span>``);``    ``<span class="keyword">return</span>` `<span class="string">"step1"</span>``;``  ``&#125; ``<span class="keyword">catch</span>` `(IOException e) &#123;``　　   System.out.println(``<span class="string">"io exception"</span>``);　　   ``     ``<span class="keyword">return</span>` `<span class="string">"step2"</span>``;``  ``&#125;``<span class="keyword">catch</span>` `(FileNotFoundException e) &#123;``    ``System.out.println(``<span class="string">"file not found"</span>``);　　　　   ``    ``<span class="keyword">return</span>` `<span class="string">"step3"</span>``;``  ``&#125;``<span class="keyword">finally</span>``&#123;``    ``System.out.println(``<span class="string">"finally block"</span>``);``    ``<span class="comment">//return "finally";``  ``&#125;`</span></span><br></pre></td></tr></table></figure>
<p>　　第二个catch的FileNotFoundException将永远不会被捕获到，因为FileNotFoundException是IOException的子类。</p>
<ol start="5">
<li>避免多次在日志信息中记录同一个异常</li>
</ol>
<p>　　只<strong>在异常最开始发生的地方进行日志信息记录。</strong>很多情况下异常都是层层向上跑出的，如果在每次向上抛出的时候，都Log到日志系统中，则会导致无从查找异常发生的根源。</p>
<ol start="6">
<li>异常处理尽量放在高层进行</li>
</ol>
<p>　　尽量<strong>将异常统一抛给上层调用者，由上层调用者统一之时如何进行处理。</strong>如果在每个出现异常的地方都直接进行处理，会导致程序异常处理流程混乱，不利于后期维护和异常错误排查。由上层统一进行处理会使得整个程序的流程清晰易懂。</p>
<ol start="7">
<li>在finally中释放资源</li>
</ol>
<p>　　如果有使用文件读取、网络操作以及数据库操作等，记得在finally中释放资源。这样不仅会使得程序占用更少的资源，也会避免不必要的由于资源未释放而发生的异常情况。                  </p>

        </div>

        <blockquote class="post-copyright">
    
    <div class="content">
        

        
        这里可以写作者留言，标签和 hexo 中所有变量及辅助函数等均可调用，示例：<a href="/2019/04/10/java异常/" target="_blank" rel="external">http://yoursite.com/2019/04/10/java异常/</a>
        
    </div>
    
    <footer>
        <a href="http://yoursite.com">
            <img src="/img/myblog.jpeg" alt="YGQ">
            YGQ
        </a>
    </footer>
</blockquote>

        


        <div class="post-footer">
            
	<ul class="article-tag-list"><li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/Java异常/">Java异常</a></li></ul>


            
<div class="page-share-wrap">
    

<div class="page-share" id="pageShare">
    <ul class="reset share-icons">
      <li>
        <a class="weibo share-sns" target="_blank" href="http://service.weibo.com/share/share.php?url=http://yoursite.com/2019/04/10/java异常/&title=《java异常》 — YGQ's Notes&pic=http://yoursite.com/img/myblog.jpeg" data-title="微博">
          <i class="icon icon-weibo"></i>
        </a>
      </li>
      <li>
        <a class="weixin share-sns wxFab" href="javascript:;" data-title="微信">
          <i class="icon icon-weixin"></i>
        </a>
      </li>
      <li>
        <a class="qq share-sns" target="_blank" href="http://connect.qq.com/widget/shareqq/index.html?url=http://yoursite.com/2019/04/10/java异常/&title=《java异常》 — YGQ's Notes&source=整理了java异常的相关知识" data-title=" QQ">
          <i class="icon icon-qq"></i>
        </a>
      </li>
      <li>
        <a class="facebook share-sns" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http://yoursite.com/2019/04/10/java异常/" data-title=" Facebook">
          <i class="icon icon-facebook"></i>
        </a>
      </li>
      <li>
        <a class="twitter share-sns" target="_blank" href="https://twitter.com/intent/tweet?text=《java异常》 — YGQ's Notes&url=http://yoursite.com/2019/04/10/java异常/&via=http://yoursite.com" data-title=" Twitter">
          <i class="icon icon-twitter"></i>
        </a>
      </li>
      <li>
        <a class="google share-sns" target="_blank" href="https://plus.google.com/share?url=http://yoursite.com/2019/04/10/java异常/" data-title=" Google+">
          <i class="icon icon-google-plus"></i>
        </a>
      </li>
    </ul>
 </div>



    <a href="javascript:;" id="shareFab" class="page-share-fab waves-effect waves-circle">
        <i class="icon icon-share-alt icon-lg"></i>
    </a>
</div>



        </div>
    </div>

    
<nav class="post-nav flex-row flex-justify-between">
  
    <div class="waves-block waves-effect prev">
      <a href="/2019/05/02/理解反射/" id="post-prev" class="post-nav-link">
        <div class="tips"><i class="icon icon-angle-left icon-lg icon-pr"></i> Prev</div>
        <h4 class="title">理解反射</h4>
      </a>
    </div>
  

  
    <div class="waves-block waves-effect next">
      <a href="/2019/04/01/volatile关键字与java内存模型/" id="post-next" class="post-nav-link">
        <div class="tips">Next <i class="icon icon-angle-right icon-lg icon-pl"></i></div>
        <h4 class="title">volatile关键字与java内存模型</h4>
      </a>
    </div>
  
</nav>



    




















</article>



</div>

        <footer class="footer">
    <div class="top">
        

        <p>
            
            <span>このブログの内容物は<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ja">クリエイティブ・コモンズ 表示 - 非営利 - 継承 4.0 国際ライセンスの下に提供されています</a></span>
        </p>
    </div>
    <div class="bottom">
        <p><span>YGQ &copy; 2015 - 2019</span>
            <span>
                
                Power by <a href="http://hexo.io/" target="_blank">Hexo</a> Theme <a href="https://github.com/yscoder/hexo-theme-indigo" target="_blank">indigo</a>
            </span>
        </p>
    </div>
</footer>

    </main>
    <div class="mask" id="mask"></div>
<a href="javascript:;" id="gotop" class="waves-effect waves-circle waves-light"><span class="icon icon-lg icon-chevron-up"></span></a>



<div class="global-share" id="globalShare">
    <ul class="reset share-icons">
      <li>
        <a class="weibo share-sns" target="_blank" href="http://service.weibo.com/share/share.php?url=http://yoursite.com/2019/04/10/java异常/&title=《java异常》 — YGQ's Notes&pic=http://yoursite.com/img/myblog.jpeg" data-title="微博">
          <i class="icon icon-weibo"></i>
        </a>
      </li>
      <li>
        <a class="weixin share-sns wxFab" href="javascript:;" data-title="微信">
          <i class="icon icon-weixin"></i>
        </a>
      </li>
      <li>
        <a class="qq share-sns" target="_blank" href="http://connect.qq.com/widget/shareqq/index.html?url=http://yoursite.com/2019/04/10/java异常/&title=《java异常》 — YGQ's Notes&source=整理了java异常的相关知识" data-title=" QQ">
          <i class="icon icon-qq"></i>
        </a>
      </li>
      <li>
        <a class="facebook share-sns" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http://yoursite.com/2019/04/10/java异常/" data-title=" Facebook">
          <i class="icon icon-facebook"></i>
        </a>
      </li>
      <li>
        <a class="twitter share-sns" target="_blank" href="https://twitter.com/intent/tweet?text=《java异常》 — YGQ's Notes&url=http://yoursite.com/2019/04/10/java异常/&via=http://yoursite.com" data-title=" Twitter">
          <i class="icon icon-twitter"></i>
        </a>
      </li>
      <li>
        <a class="google share-sns" target="_blank" href="https://plus.google.com/share?url=http://yoursite.com/2019/04/10/java异常/" data-title=" Google+">
          <i class="icon icon-google-plus"></i>
        </a>
      </li>
    </ul>
 </div>


<div class="page-modal wx-share" id="wxShare">
    <a class="close" href="javascript:;"><i class="icon icon-close"></i></a>
    <p>扫一扫，分享到微信</p>
    <img src="//api.qrserver.com/v1/create-qr-code/?data=http://yoursite.com/2019/04/10/java异常/" alt="微信分享二维码">
</div>




    <script src="//cdn.bootcss.com/node-waves/0.7.4/waves.min.js"></script>
<script>
var BLOG = { ROOT: '/', SHARE: true, REWARD: false };


</script>

<script src="//unpkg.com/hexo-theme-material-indigo@latest/js/main.min.js"></script>


<div class="search-panel" id="search-panel">
    <ul class="search-result" id="search-result"></ul>
</div>
<template id="search-tpl">
<li class="item">
    <a href="{path}" class="waves-block waves-effect">
        <div class="title ellipsis" title="{title}">{title}</div>
        <div class="flex-row flex-middle">
            <div class="tags ellipsis">
                {tags}
            </div>
            <time class="flex-col time">{date}</time>
        </div>
    </a>
</li>
</template>

<script src="//unpkg.com/hexo-theme-material-indigo@latest/js/search.min.js" async></script>








<script>
(function() {
    var OriginTitile = document.title, titleTime;
    document.addEventListener('visibilitychange', function() {
        if (document.hidden) {
            document.title = '诶去哪里了！';
            clearTimeout(titleTime);
        } else {
            document.title = '(つェ⊂)咦!又好了!';
            titleTime = setTimeout(function() {
                document.title = OriginTitile;
            },2000);
        }
    });
})();
</script>



</body>
</html>
